### ISSUE TITLE
Sorting photos

### ISSUE THREAD

**Issue by Milording** [JuniperPhoton/MyerSplashUWP#7]
It would be nice to have likes sort button in page with photos!

**Comment by JuniperPhoton** [comment]
Sort with what?

2017年6月11日 06:39，Milording <notifications@github.com>写道：

It would be nice to have sort button in page with photos!

**Comment by Milording** [comment]
Amount of likes.

**Comment by JuniperPhoton** [comment]
This need backend support of Unsplash, which I think it's currently not available.
