### ISSUE TITLE
[Exception throws] Can't save image

### ISSUE THREAD

**Issue by rosuH** [JuniperPhoton/MyerSplashUWP#8]
OS：Win10 Pro 1703 ( 15063.413) x64
MyerSplashUWP Version:  2.6.2

Issues : 
When I try to save image, the app notified that:

> Exception throws.The file name, directory name, or volume label syntax is incorrect

and the show the download information:

> Downloading in background...

but it was not downloading.

![snipaste_20170614_190323.png](https://ooo.0o0.ooo/2017/06/14/594119a6a9640.png)

Chinese Version:
当我想要下载图片的时候，程序弹出提示

> Exception throws.文件名、目录名或卷标语法不正确

然后这个提示消失，进入正常下载的步骤，但是并没有下载。因为看到没有此程序没有流量产生（已排除网络问题）。

- - - - 
此外，设置里的文件保存路径无法更改：

![snipaste_20170614_191334.png](https://ooo.0o0.ooo/2017/06/14/59411a64980da.png)

- - - - -
感谢。 🌹

**Comment by JuniperPhoton** [comment]
目前文件名的命名以作者的名字为前缀，然后可能导致一些非法字符无法作为文件名，这个我下个版本修复一下。感谢。
